
Exception Time :   15/1/2020 06:42

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 73

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:47

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:52

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:55

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:55

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 07:33

Exception Message :   
The remote name could not be resolved: 'kuwaitportal.paci.gov.kw'

Exception InnerException :   


Exception StackTrace :   
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at MapIt.Helpers.PresentHelper.GenerateToken() in F:\MapIt\MapItWebsite\MapIt\MapIt.Helpers\PresentHelper.cs:line 405

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 07:34

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 118

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 07:39

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 116

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:31

Exception Message :   
Object reference not set to an instance of an object.

Exception InnerException :   


Exception StackTrace :   
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 140

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:44

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 145

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:53

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 158

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:57

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 158

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 10:10

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Buy.aspx.cs:line 157

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 10:10

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:01

Exception Message :   
Object reference not set to an instance of an object.

Exception InnerException :   


Exception StackTrace :   
   at MapIt.Web.Payment.Buy.SendRequest() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Buy.aspx.cs:line 116

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:22

Exception Message :   
Object reference not set to an instance of an object.

Exception InnerException :   


Exception StackTrace :   
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 70

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:22

Exception Message :   
Object reference not set to an instance of an object.

Exception InnerException :   


Exception StackTrace :   
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 70

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:44

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 100

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:47

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 100

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:52

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse)
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 100

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:52

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse)
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 100

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:52

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:53

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:53

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 11:53

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse)
   at MapIt.Web.Payment.Response.GetResponse() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Response.aspx.cs:line 100

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:01

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Thanks.LoadData() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Thanks.aspx.cs:line 56

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:01

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:04

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:04

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:05

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:05

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Thanks.btnShowInv_Click(Object sender, EventArgs e) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Thanks.aspx.cs:line 117

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:34

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:34

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:35

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Thanks.LoadData() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Thanks.aspx.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:35

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:41

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:42

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Thanks.LoadData() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Thanks.aspx.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:43

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:43

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   16/1/2020 12:43

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   20/1/2020 08:49

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   20/1/2020 08:49

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   20/1/2020 08:50

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   20/1/2020 08:50

Exception Message :   
Failure sending mail.

Exception InnerException :   
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.64.49.18:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

Exception StackTrace :   
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at MapIt.Helpers.MailHelper.SendEmail(String From, String To, String SMTPServer, String UserName, String Password, String Subject, String Body, String AttachmentFilePath) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Helpers\MailHelper.cs:line 51

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   20/1/2020 08:50

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Thanks.btnShowInv_Click(Object sender, EventArgs e) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Payment\Thanks.aspx.cs:line 112

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   26/1/2020 09:38

Exception Message :   
An error occurred while updating the entries. See the inner exception for details.

Exception InnerException :   
System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
ClientConnectionId:7b5463e9-3b8b-4cbf-adb4-59d205bfdf3d
Error Number:8152,State:13,Class:16

Exception StackTrace :   
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges()
   at MapIt.Repository.Repository`1.Add(T entity) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Repository\Repository.cs:line 101
   at MapIt.Web.Register.Save() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Register.aspx.cs:line 171

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   26/1/2020 09:40

Exception Message :   
An error occurred while updating the entries. See the inner exception for details.

Exception InnerException :   
System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
ClientConnectionId:3e37d2aa-e21c-41b1-b3f9-f59f74e050c7
Error Number:8152,State:13,Class:16

Exception StackTrace :   
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges()
   at MapIt.Repository.Repository`1.Add(T entity) in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Repository\Repository.cs:line 101
   at MapIt.Web.Register.Save() in D:\MohammedHassan\MapIt\MapItWebsite\MapIt.Web\Register.aspx.cs:line 171

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Time :   26/1/2020 09:44

Data Message :   
Arab Standard Time,United States,172.22.197.17,DC-FF-GIS020

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
